# Generated by Django 2.1 on 2018-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Animation', 'Crée et anime'), ('Wellbeing', 'Veille au bien-être'), ('Commitment', 'Vit un engagement'), ('Evaluation', 'Evalue'), ('Fun', "Favorise l'amusement"), ('Other', "Fait d'autres trucs")], max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('training', models.CharField(choices=[('Noel', 'Noel'), ('Carnaval1', 'Carnaval 1e'), ('Formactive1', 'Form@ctive 1e'), ('Toussaint', 'Toussaint'), ('Carnaval2', 'Carnval 2e'), ('Formactive2', 'Form@ctive 2e')], max_length=50)),
            ],
            options={
                'ordering': ('name', 'training'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('advices', models.CharField(max_length=1024)),
                ('fields', models.ManyToManyField(to='planforma.Field')),
            ],
            options={
                'ordering': ('name', 'advices'),
            },
        ),
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(to='planforma.Skill'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='skills',
            field=models.ManyToManyField(to='planforma.Skill'),
        ),
    ]
