# Generated by Django 2.1 on 2018-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name', 'long_name'),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name', 'training'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('advices', models.CharField(max_length=1024)),
                ('fields', models.ManyToManyField(to='planforma.Field')),
            ],
            options={
                'ordering': ('name', 'advices'),
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(to='planforma.Skill'),
        ),
        migrations.AddField(
            model_name='module',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planforma.Training'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='skills',
            field=models.ManyToManyField(to='planforma.Skill'),
        ),
    ]
